# -*- coding: utf-8 -*-
"""handwritten digits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-gm9WgoB1LIzWqFcC3dMTlT3fkTaQxP
"""

!pip install tensorflow

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from google.colab import files

mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = tf.keras.utils.normalize(x_train, axis=1)
x_test = tf.keras.utils.normalize(x_test, axis=1)

# build model
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(10, activation='softmax'))

# compile model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# train model
model.fit(x_train, y_train, epochs=3)

# evaluate model
val_loss, val_acc = model.evaluate(x_test, y_test)
print(val_loss, val_acc)

# # save model
# model_name = 'handwritten_digits_reader.model'
# model.save(model_name)
# files.download(model_name)
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Define the path to save the model
model_path = '/content/drive/My Drive/handwritten_digits_reader.model'

# Save the model
model.save(model_path)

print(f"Model saved to {model_path}. You can download it from Google Drive.")

# save model
model_name = 'handwritten_digits_reader.keras'
model.save(model_name)
files.download(model_name)

model = tf.keras.models.load_model('handwritten_digits_reader.model')
loss, accuracy = model.evaluate(x_test, y_test)
print(loss)
print(accuracy)